import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parse } from "yaml";
import openapiTS, { astToString } from "openapi-typescript";
import { compileOpenApiSchemas } from "../src/openapi-validation.js";

type Schema = { enum?: unknown[]; properties?: Record<string, Schema> };
type Operation = { operationId?: string };
type Document = {
  components?: { schemas?: Record<string, Schema> };
  paths?: Record<string, Record<string, Operation>>;
};

const root = resolve(import.meta.dirname, "..");
const outputPath = resolve(root, "src/generated/contract-options.ts");
const typesPath = resolve(root, "src/generated/openapi.d.ts");
const openapiPath = resolve(root, "openapi.yaml");
const source = await readFile(openapiPath, "utf8");
const document = parse(source) as Document;
compileOpenApiSchemas(document as Record<string, unknown>);

function enumValues(name: string): string[] {
  const values = document.components?.schemas?.[name]?.enum;
  if (!Array.isArray(values) || values.some((value) => typeof value !== "string")) {
    throw new Error(`OpenAPI schema ${name} must define a string enum`);
  }
  return values as string[];
}

const generated = `// Generated by scripts/generate-contract.ts. Do not edit.\n\nexport const CAMPAIGN_KINDS = ${JSON.stringify(enumValues("CampaignKind"))} as const;\n\nexport const CAPABILITY_ASSET_TYPES = ${JSON.stringify(enumValues("CapabilityAssetType"))} as const;\n`;
const generatedTypes = astToString(await openapiTS(source));

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) throw new Error("Generated contract artifact is stale; run npm run generate");
  const currentTypes = await readFile(typesPath, "utf8").catch(() => "");
  if (currentTypes !== generatedTypes) throw new Error("Generated OpenAPI types are stale; run npm run generate");
} else {
  await mkdir(resolve(root, "src/generated"), { recursive: true });
  await writeFile(outputPath, generated);
  await writeFile(typesPath, generatedTypes);
}
